#Competency Question 1 - WHAT are the different types of privacy
SELECT ?PrivType WHERE {?PrivType rdfs:subClassOf privacy:PrivacyType}

#Competency Question 2 - WHAT are the different interrogatives?
SELECT ?Interrogatives WHERE {?Interrogatives rdfs:subClassOf privacy:InterrogativeDimensions}

#Competency Question 3 - What are all the unique relationships between Privacy Types and Interrogatives? 
SELECT ?Type ?Relationship ?Interrogative WHERE {?Relationship rdfs:range ?Type . ?Relationship rdfs:domain ?Interrogative}

#Competency Question 4 - For a given Interrogative, what are the related privacy types? 
SELECT ?Relationship ?Type WHERE {?Relationship rdfs:domain privacy:Identity . ?Relationship rdfs:range ?Type}

#Competency Question 5 - For a given Privacy Type, what are the related Interrogatives? 
SELECT ?Relationship ?Interrogative WHERE {?Relationship rdfs:range privacy:PersonalPrivacy . ?Relationship rdfs:domain ?Interrogative}